<?php
$image_basepath  = './images/';
$sr_image_width = 0;
$sr_image_height = 0;
$showrooms = array (
    'ceiss' => array (
        'title' => "Оптика «Цейс»",
        'display_in_list' => 0,
        'coords' => array (),
        47 => array (
            'location' => "Проспект Просвещения, д.34",
            'title_showroom' => 'Оптика ZEISS',
            'metro' => 'Проспект Просвещения',
            'placement' => '',
            'phone' => "497-63-01",
            'latitude' => 60.0536921,
            'longitude' => 30.3338420,
            'accuracy' => 14,
            'img' => '',
        ),
        61 => array (
            'location' => "Коломяжский проспект, д.20",
            'title_showroom' => 'Оптика ZEISS',
            'metro' => 'Пионерсксая',
            'placement' => '',
            'phone' => "301-03-74",
            'latitude' => 59.9986835,
            'longitude' => 30.2983681,
            'accuracy' => 13,
            'img' => '',
        ),
        64 => array (
            'location' => "Владимирский проспект, д.13",
            'title_showroom' => 'Оптика ZEISS',
            'metro' => 'Владимирская',
            'placement' => '',
            'phone' => "310-56-52",
            'latitude' => 59.9298712,
            'longitude' => 30.3471790,
            'accuracy' => 14,
            'img' => '',
        ),
        65 => array (
            'location' => 'Суворовский проспект, д.8',
            'title_showroom' => 'Оптика ZEISS',
            'metro' => 'Площадь Восстания',
            'placement' => '',
            'phone' => "322-55-40",
            'latitude' => 59.9333647,
            'longitude' => 30.3689381,
            'accuracy' => 14,
            'img' => '',
        ),
    ),
    'admiralteisky' => array (
        'title' => "Адмиралтейский район",
        'display_in_list' => 1,
        'coords' => array (), // потенциальные координаты района (для клика по li в списке районов
        70 => array (         // номер статьи, описывающей салон
            'location' => 'Сенная площадь, д.2, место 113',
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Сенная площадь',
            'placement' => 'ТК ПИК',
            'phone' => "449-24-54",
            'latitude' => 59.9270236,
            'longitude' => 30.3202838,
            'accuracy' => 13,
            'img' => '',
        ),
    ),
    'vasileostr' => array (
        'title' => "Василеостровский район",
        'display_in_list' => 1,
        'coords' => array (),
        46 => array (
            'location' => "Васильевский остров, 6 линия, д.27",
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Василеостровская',
            'placement' => '',
            'phone' => "323-37-20",
            'latitude' => 59.942536,
            'longitude' => 30.280336,
            'accuracy' => 17,
            'img' => '',
        ),
        54 => array (
            'location' => "Васильевский остров, Средний пр., д.47",
            'title_showroom' => 'Оптика «Kodak Lens»',
            'metro' => 'Василеостровская',
            'placement' => '',
            'phone' => "323-12-53",
            'latitude' => 59.941741,
            'longitude' => 30.273115,
            'accuracy' => 15,
            'img' => '',
        )
    ),
    'vyborgsky' => array (
        'title' => "Выборгский район",
        'display_in_list' => 1,
        'coords' => array (),
        47 => array (
            'location' => "Проспект Просвещения, д.34",
            'title_showroom' => 'Оптика ZEISS',
            'metro' => 'Проспект Просвещения',
            'placement' => '',
            'phone' => "497-63-01",
            'latitude' => 60.0536921,
            'longitude' => 30.3338420,
            'accuracy' => 14,
            'img' => '',
        ),
        48 => array (
            'location' => 'Выборгское шоссе, д.3',
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Озерки',
            'placement' => 'Гипермаркет «ОКЕЙ»',
            'phone' => "703-70-56",
            'latitude' => 60.037488,
            'longitude' => 30.321357,
            'accuracy' => 16,
            'img' => '',
        ),
        82 => array (
            'location' => 'Проспект Энгельса, д.150',
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Проспект Просвещения',
            'placement' => '',
            'phone' => "680-11-37",
            'latitude' => 60.0557190,
            'longitude' => 30.3360906,
            'accuracy' => 14,
            'img' => '',
        )
    ),
    'kalininsky' => array (
        'title' => "Калининский район",
        'display_in_list' => 1,
        'coords' => array (),
        50 => array (
            'location' => "Гражданский проспект, д.36",
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Академическая',
            'placement' => '',
            'phone' => "534-18-61",
            'latitude' => 60.011068,
            'longitude' => 30.394253,
            'accuracy' => 15,
            'img' => '',
        )
    ),
    'kirovsky' => array (
        'title' => "Кировский район",
        'display_in_list' => 1,
        'coords' => array (),
        51 => array (
            'location' => "Ленинский проспект, д.131",
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Ленинский проспект',
            'placement' => '',
            'phone' => "372-20-83",
            'latitude' => 59.8513803,
            'longitude' => 30.2737999,
            'accuracy' => 14,
            'img' => '',
        ),
        52 => array (
            'location' => 'Проспект Маршала Жукова, д.31',
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Автово',
            'placement' => 'Гипермаркет «ОКЕЙ»',
            'phone' => "703-79-08",
            'latitude' => 59.8485126,
            'longitude' => 30.2165046,
            'accuracy' => 14,
            'img' => '',
        ),
    ),
    'krasnogvard' => array (
        'title' => "Красногвардейский район",
        'display_in_list' => 1,
        'coords' => array (),
        53 => array (
            'location' => "Заневский проспект, д.8",
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Новочеркасская',
            'placement' => '',
            'phone' => "528-47-69",
            'latitude' => 59.9284483,
            'longitude' => 30.4078312,
            'accuracy' => 14,
            'img' => '',
        )
    ),
    'moskovsky' => array (
        'title' => "Московский район",
        'display_in_list' => 1,
        'coords' => array (),
        55 => array (
            'location' => 'Улица Типанова, д.21',
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Московская',
            'placement' => 'ТК &quot;ПИТЕР»',
            'phone' => "335-68-31",
            'latitude' => 59.8524896,
            'longitude' => 30.3461463,
            'accuracy' => 14,
            'img' => '',
        ),
        56 => array (
            'location' => 'Московский проспект, д.220',
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Московская',
            'placement' => 'Универмаг &quot;Московский»',
            'phone' => "327-94-45",
            'latitude' => 59.8468472,
            'longitude' => 30.3225101,
            'accuracy' => 13,
            'img' => '',
        ),
        57 => array (
            'location' => 'Пулковское шоссе, д.17',
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => '',
            'placement' => 'Гипермаркет «ОКЕЙ»',
            'phone' => "336-88-93",
            'latitude' => 59.7933342,
            'longitude' => 30.3244945,
            'accuracy' => 13,
            'img' => '',
        ),
        58 => array (
            'location' => 'Московский проспект, д.137',
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Электросила',
            'placement' => 'Гипермаркет «ОКЕЙ»',
            'phone' => "336-88-54",
            'latitude' => 59.8813162,
            'longitude' => 30.3171105,
            'accuracy' => 13,
            'img' => '',
        ),
        59 => array (
            'location' => 'Проспект Космонавтов, д.45',
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Московская',
            'placement' => 'Гипермаркет «ОКЕЙ»',
            'phone' => "336-80-43",
            'latitude' => 59.8502393,
            'longitude' => 30.3534016,
            'accuracy' => 13,
            'img' => '',
        ),
    ),
    'nevsky' => array (
        'title' => "Невский район",
        'display_in_list' => 1,
        'coords' => array (),
        60 => array (
            'location' => "Проспект Большевиков, д.10, корп.1",
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Проспект Большевиков',
            'placement' => 'Гипермаркет «ОКЕЙ»',
            'phone' => "380-68-34",
            'latitude' => 59.912661,
            'longitude' => 30.477355,
            'accuracy' => 13,
            'img' => '',
        )
    ),
    'petrogradsky' => array (
        'title' => "Петроградский район",
        'display_in_list' => 1,
        'coords' => array (),
        79 => array (
            'location' => "Каменноостровский пр., д.37",
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Петроградская',
            'placement' => 'Дом Мод',
            'phone' => "329-30-98",
            'latitude' => 59.9666246,
            'longitude' => 30.3113949,
            'accuracy' => 15,
            'img' => '',
        ),
        69 => array (
            'location' => "Каменноостровский пр., д.42б",
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Петроградская',
            'placement' => '',
            'phone' => "346-19-57",
            'latitude' => 59.9679799,
            'longitude' => 30.3080038,
            'accuracy' => 14,
            'img' => '',
        ),
        77 => array (
            'location' => "Проспект Добролюбова, д.27",
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Спортивная',
            'placement' => '',
            'phone' => "498-16-94",
            'latitude' => 59.9507096,
            'longitude' => 30.2968882,
            'accuracy' => 14,
            'img' => '',
        )
    ),
    'primorsky' => array (
        'title' => "Приморский район",
        'display_in_list' => 1,
        'coords' => array (),
        78 => array (
            'location' => "Савушкина, д. 126",
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Старая деревня',
            'placement' => 'ТРК «Atlantic City»',
            'phone' => "334-26-43",
            'latitude' => 59.988527,
            'longitude' => 30.204073,
            'accuracy' => 14,
            'img' => '',
        ),
        61 => array (
            'location' => "Коломяжский проспект, д.20",
            'title_showroom' => 'Оптика ZEISS',
            'metro' => 'Пионерсксая',
            'placement' => '',
            'phone' => "301-03-74",
            'latitude' => 59.9986835,
            'longitude' => 30.2983681,
            'accuracy' => 13,
            'img' => '',
        ),
        62 => array (
            'location' => 'Серебристый бульвар, д.21',
            'title_showroom' => 'Оптика Kodak Lens',
            'metro' => 'Пионерская',
            'placement' => '',
            'phone' => "301-00-65",
            'latitude' => 60.007153,
            'longitude' => 30.28308,
            'accuracy' => 15,
            'img' => '',
        ),
        63 => array (
            'location' => 'Улица Савушкина, д.119',
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Старая деревня',
            'placement' => 'Гипермаркет «ОКЕЙ»',
            'phone' => "336-88-97",
            'latitude' => 59.987357,
            'longitude' => 30.226561,
            'accuracy' => 13,
            'img' => '',
        )
    ),
    'centralny' => array (
        'title' => "Центральный район",
        'display_in_list' => 1,
        'coords' => array (),
        64 => array (
            'location' => "Владимирский проспект, д.13",
            'title_showroom' => 'Оптика ZEISS',
            'metro' => 'Владимирская',
            'placement' => '',
            'phone' => "310-56-52",
            'latitude' => 59.9298712,
            'longitude' => 30.3471790,
            'accuracy' => 14,
            'img' => '',
        ),
        65 => array (
            'location' => 'Суворовский проспект, д.8',
            'title_showroom' => 'Оптика ZEISS',
            'metro' => 'Площадь Восстания',
            'placement' => '',
            'phone' => "322-55-40",
            'latitude' => 59.9333647,
            'longitude' => 30.3689381,
            'accuracy' => 14,
            'img' => '',
        ),
        66 => array (
            'location' => 'Улица Жуковского, д.6',
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Маяковская',
            'placement' => '',
            'phone' => "272-57-66",
            'latitude' => 59.936132,
            'longitude' => 30.350801,
            'accuracy' => 14,
            'img' => '',
        ),
        67 => array (
            'location' => 'Разъезжая улица, д.43',
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Лиговский проспект',
            'placement' => '',
            'phone' => "575-50-16",
            'latitude' => 59.920993,
            'longitude' => 30.352646,
            'accuracy' => 15,
            'img' => '',
        ),
        68 => array (
            'location' => 'Лиговский проспект, д.76',
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Лиговский проспект',
            'placement' => '',
            'phone' => "712-08-74",
            'latitude' => 59.921692,
            'longitude' => 30.355328,
            'accuracy' => 15,
            'img' => '',
        ),
        71 => array (
            'location' => 'Невская линия, 1 этаж',
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Невский проспект',
            'placement' => 'Большой Гостиный Двор',
            'phone' => "710-53-23",
            'latitude' => 59.9333321,
            'longitude' => 30.3299935,
            'accuracy' => 14,
            'img' => '',
        ),
        72 => array (
            'location' => 'Садовая линия, 1 этаж',
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => 'Невский проспект',
            'placement' => 'Большой Гостиный Двор',
            'phone' => "710-52-89",
            'latitude' => 59.934175,
            'longitude' => 30.332605,
            'accuracy' => 15,
            'img' => '',
        ),
        73 => array (
            'roomtype' => 'Оптика «Новый Взгляд»',
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'location' => 'ул. Марата, д.86',
            'metro' => 'Пушкинская',
            'placement' => 'ТК НЕПТУН',
            'phone' => "448-03-11",
            'latitude' => 59.9193113,
            'longitude' => 30.3389582,
            'accuracy' => 14,
            'img' => '',
        ),
    ),
    'prigorod' => array (
        'title' => "Пригороды",
        'display_in_list' => 1,
        'coords' => array (),
        74 => array (
            'location' => "СЕСТРОРЕЦК, улица Воскова, д.5",
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => '',
            'placement' => '',
            'phone' => "340-73-61",
            'latitude' => 60.0930037,
            'longitude' => 29.9617054,
            'accuracy' => 15,
            'img' => '',
        ),
        81 => array (
            'location' => "КОЛПИНО, Бульвар Трудящихся, д.15",
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => '',
            'placement' => '',
            'phone' => "482-39-04",
            'latitude' => 59.736149,
            'longitude' => 30.570785,
            'accuracy' => 15,
            'img' => '',
        ),
        80 => array (
            'location' => "СЕСТРОРЕЦК, улица Володарского, д.20",
            'title_showroom' => 'Оптика «Зайди-Увидишь»',
            'metro' => '',
            'placement' => 'ТК СЕЗОН',
            'phone' => "437-35-07",
            'latitude' => 60.100535,
            'longitude' => 29.972674,
            'accuracy' => 15,
            'img' => '',
        )
    ),
);
?>
